### ISSUE TITLE
Error in Firebaseio module

### ISSUE THREAD

**Issue by sanguinarius** [c0dejump/HawkScan#1]
Hi, 

They have an error with Firebaseio check module.
When we use an FQDN with sub domain your module parse and use only subdomain for example:

**https://bad.hawkscan.com Firebaseio module check https://bad.firebaseio.com/.json**

**Comment by c0dejump** [comment]
Thanks for reporting!

Normaly it's corrected now, if you see otherthings don't hesitate.
