### ISSUE TITLE
Unable to install OpenSSL module

### ISSUE THREAD

**Issue by mechb0y** [c0dejump/HawkScan#10]
While running your tool, I'm getting this error

```
Traceback (most recent call last):
  File "hawkscan.py", line 31, in <module>
    from modules.before_run import before_start
  File "/root/Tools/HawkScan/modules/before_run.py", line 5, in <module>
    import ssl, OpenSSL
ImportError: No module named 
```

**Comment by c0dejump** [comment]
Hi mechb0y,

Can you give me your python version please ?

did you try to do "pip install pyOpenSSL" ?

Thanks, best regards.

**Comment by mechb0y** [comment]
Hi c0dejump,

* did you try to do "pip install pyOpenSSL"?
Yeah, I tried but not working(:

I'm using,
Python 2.7.17
Python 3.6.9

Regards,
mechboy

**Comment by c0dejump** [comment]
Hello,

Sorry for the delay

Maybe try to update python & pip version ?

Thanks, best regards.

**Comment by c0dejump** [comment]
Hello,

If it's ok for you, I'll close this case,

Thansk using HawkScan and thanks for your reporting.

Best Regards.
