### ISSUE TITLE
dryscrape cannot be installed

### ISSUE THREAD

**Issue by HyWell** [c0dejump/HawkScan#3]
dryscrape depends on webkit-server , webkit-server  need qt<=5.5.can use  Spynner?

**Comment by c0dejump** [comment]
Hello HyWell,

Thanks for your report!

Have you seen:
"
If you have problem to install the library "dryscrape" you can follow this link:https://www.it-swarm.dev/fr/python/pip-install-dryscrape-echoue-avec-error-errno-2-ce-fichier-ou-repertoire-srcwebkit-server/827034588/
"?

I will check for Spynner, "dryscrape" is my principal preoccupation for the moment.

Thanks, Best regards :)

**Comment by HyWell** [comment]
OS system:MacOS Catalina
My can only use webengine, not web-server

**Comment by c0dejump** [comment]
Hello,

I put a "setup.py".

So, for the moment MacOS not having the feature "webkit/webengine" sorry, but you can install and execute it.

For the Spynner it's in my TODO :) 

Thanks for your issue and if you have other comment don't hesitate !

Regards.
