### ISSUE TITLE
Could not install packages due to an EnvironmentError: 404 

### ISSUE THREAD

**Issue by Naeemk10** [c0dejump/HawkScan#4]
Dear Team 

**thanks of lot make this tool .**

when i install this tool from use this command :- python setup.py 
see this error 

Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (2.22.0)
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages (19.0.0)
Collecting pprint
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/pprint/

**We troubleshooting but cant solve tis issue .**

1:- we try run from python 2.7 issue not solve 
2:- we try edit reqirements file and remove pprint  pkg issue not solve 

kindly please shared solutions  as soon possible.

**Comment by c0dejump** [comment]
Hello,

Thanks to you !

What is you OS please ?
You execute it in "sudo" ?

I look at it as quickly as possible !

Thanks, best regards.

**Comment by Naeemk10** [comment]
Hi there

I'm use kali linux.
Debian distro.

If possible kindly shared solution. I wanted to use this tool

**Comment by c0dejump** [comment]
Hello,

Did you do a update/upgrade ?

And pprint is included in Python 2.7. If you try removing pprint from the requirements.txt file, it's work?

Thanks, Best regards.

**Comment by Naeemk10** [comment]
Dear Team

We already remove pprint from requirements but when I run python setup.py
scrip
Show same error.

**Comment by c0dejump** [comment]
For "pprint" librarie it's ok now, 

For "dryscraper" you can follow this link "https://www.it-swarm.dev/fr/python/pip-install-dryscrape-echoue-avec-error-errno-2-ce-fichier-ou-repertoire-srcwebkit-server/827034588/" in my "**Usage**" title.

Thanks, Best regards.
