### ISSUE TITLE
setup.py has unexpected content

### ISSUE THREAD

**Issue by Hackndo** [c0dejump/HawkScan#5]
Hello,
I see that `setup.py` file as actually some `system` command running as sudo, which is not a good practice.

`setup.py` is a well known file for packaging python applications (https://packaging.python.org/tutorials/packaging-projects/) and it should be used as so.

Running `sudo pip` via `os.system` should absolutely be removed, as it installs libraries for root user, even if the current user has a virtual environment.

I will probably try and use it when it's well packaged :)

Keep up the good work!

**Comment by c0dejump** [comment]
Hello,

Ah yes, you're right, it fixed thanks !

Don't hesitate if you have another comment or advices :)

Thanks,
Best regards.
